import {
  boolean,
  index,
  integer,
  jsonb,
  numeric,
  pgTable,
  serial,
  text,
  timestamp,
  uniqueIndex,
  varchar,
} from "drizzle-orm/pg-core";

export const businesses = pgTable(
  "businesses",
  {
    id: serial("id").primaryKey(),
    neshanId: varchar("neshan_id", { length: 160 }),
    name: varchar("name", { length: 320 }).notNull(),
    category: varchar("category", { length: 120 }).notNull(),
    address: text("address").notNull(),
    city: varchar("city", { length: 120 }).notNull().default("تهران"),
    latitude: numeric("latitude", { precision: 10, scale: 7 }),
    longitude: numeric("longitude", { precision: 10, scale: 7 }),
    phone: varchar("phone", { length: 80 }),
    website: varchar("website", { length: 512 }),
    websiteTitle: varchar("website_title", { length: 320 }),
    websiteFound: boolean("website_found").notNull().default(false),
    websiteStatus: varchar("website_status", { length: 40 }).notNull().default("unknown"),
    websiteQuality: varchar("website_quality", { length: 32 }).notNull().default("بررسی نشده"),
    websitePrompt: text("website_prompt"),
    qualityScore: integer("quality_score").notNull().default(0),
    digitalMaturity: integer("digital_maturity").notNull().default(0),
    hasOnlineOrder: boolean("has_online_order").notNull().default(false),
    hasBooking: boolean("has_booking").notNull().default(false),
    hasContactPage: boolean("has_contact_page").notNull().default(false),
    hasSocialLinks: boolean("has_social_links").notNull().default(false),
    leadScore: integer("lead_score").notNull().default(0),
    technologies: jsonb("technologies").$type<string[]>().notNull().default([]),
    socialLinks: jsonb("social_links").$type<string[]>().notNull().default([]),
    source: varchar("source", { length: 80 }).notNull().default("neshan"),
    lastChecked: timestamp("last_checked", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("businesses_neshan_id_unique").on(table.neshanId),
    index("businesses_city_idx").on(table.city),
    index("businesses_category_idx").on(table.category),
    index("businesses_lead_score_idx").on(table.leadScore),
  ],
);

export const collectionRuns = pgTable(
  "collection_runs",
  {
    id: serial("id").primaryKey(),
    searchTerm: varchar("search_term", { length: 240 }).notNull(),
    latitude: numeric("latitude", { precision: 10, scale: 7 }).notNull(),
    longitude: numeric("longitude", { precision: 10, scale: 7 }).notNull(),
    source: varchar("source", { length: 80 }).notNull().default("neshan-search"),
    status: varchar("status", { length: 40 }).notNull().default("queued"),
    resultsCount: integer("results_count").notNull().default(0),
    errorMessage: text("error_message"),
    requestedAt: timestamp("requested_at", { withTimezone: true }).notNull().defaultNow(),
    completedAt: timestamp("completed_at", { withTimezone: true }),
  },
  (table) => [index("collection_runs_requested_at_idx").on(table.requestedAt)],
);
